<a href="https://colab.research.google.com/github/Rubaia-jannat/work/blob/main/Expertise_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: Write a generator expression to create cubes of numbers from 1 to 5

cubes = (x**3 for x in range(1, 6))
print(next(cubes))
print(next(cubes))


1
8


In [ ]:
with open("example.txt", "a") as file:
  file.write("\nAppending new content!")

In [ ]:
with open("example.txt", "w") as file:
    file.write("Hello, File Handling!")

# Reading from a file
with open("example.txt", "r") as file:
    content = file.read()
    print(content)  # Output: Hello, File Handling!

Hello, File Handling!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
os.mkdir("new_directory")

# Change the current working directory
os.chdir("new_directory")
print("Current Directory:", os.getcwd())

# Delete the directory
os.chdir("..")
os.rmdir("new_directory")

Current Directory: /content/new_directory


In [ ]:
import os

# 1. Create a directory called "test_dir"
directory_name = "test_dir"
if not os.path.exists(directory_name):
    os.mkdir(directory_name)
    print(f"Directory '{directory_name}' created.")
else:
    print(f"Directory '{directory_name}' already exists.")

# 2. Create a file inside the directory called "test_file.txt" and write "Hello, Python!"
file_name = os.path.join(directory_name, "test_file.txt")
with open(file_name, "w") as file:
    file.write("Hello, Python!")
    print(f"File '{file_name}' created and data written.")

# 3. Read the content back and print it
with open(file_name, "r") as file:
    content = file.read()
    print(f"Content of '{file_name}': {content}")

# 4. Delete the file and the directory
os.remove(file_name)
print(f"File '{file_name}' removed.")

os.rmdir(directory_name)
print(f"Directory '{directory_name}' removed.")


Directory 'test_dir' created.
File 'test_dir/test_file.txt' created and data written.
Content of 'test_dir/test_file.txt': Hello, Python!
File 'test_dir/test_file.txt' removed.
Directory 'test_dir' removed.


In [ ]:
import numpy as np
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
print(zeros)
print(ones)
tens =np.full((2,3),100)
print(tens)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]


In [ ]:
a = np.array ([[2,3,4],[7,8,9]])
b = np.array([[4,9,8],[7,5,4]])
print(a+b)
print(a*b)
b_transposed = b.T
print(b_transposed)
print (np.dot(a,b_transposed))

[[ 6 12 12]
 [14 13 13]]
[[ 8 27 32]
 [49 40 36]]
[[4 7]
 [9 5]
 [8 4]]
[[ 67  45]
 [172 125]]


In [ ]:
# prompt: Create a 2D NumPy array of random integers between 1 and 50.
# Perform the following:
# Find the mean of all elements.
# Transpose the array.
# Sort the array along rows.
# Extract all elements greater than 25.
# Perform matrix multiplication between the original and transposed array.

import numpy as np

# Create a 2D NumPy array of random integers between 1 and 50
array_2d = np.random.randint(1, 51, size=(5, 5))  # Example: 5x5 array

# Find the mean of all elements
mean_value = np.mean(array_2d)
print("Mean of all elements:", mean_value)

# Transpose the array
transposed_array = array_2d.T
print("\nTransposed array:\n", transposed_array)

# Sort the array along rows
sorted_array = np.sort(array_2d, axis=1)
print("\nSorted array along rows:\n", sorted_array)

# Extract all elements greater than 25
elements_greater_than_25 = array_2d[array_2d > 25]
print("\nElements greater than 25:\n", elements_greater_than_25)

# Perform matrix multiplication between the original and transposed array
matrix_product = np.dot(array_2d, transposed_array)
print("\nMatrix product of the original and transposed array:\n", matrix_product)

Mean of all elements: 26.72

Transposed array:
 [[22 41 25 20  6]
 [18 40 48  9 50]
 [46 29 15 15 36]
 [15  8 27 19 39]
 [37 28 23 12 40]]

Sorted array along rows:
 [[15 18 22 37 46]
 [ 8 28 29 40 41]
 [15 23 25 27 48]
 [ 9 12 15 19 20]
 [ 6 36 39 40 50]]

Elements greater than 25:
 [46 37 41 40 29 28 48 27 50 36 39 40]

Matrix product of the original and transposed array:
 [[4518 4112 3360 2021 4753]
 [4112 4970 4240 2103 4722]
 [3360 4240 4412 1946 5063]
 [2021 2103 1946 1211 2331]
 [4753 4722 5063 2331 6953]]


In [ ]:
# prompt: Create a 2D NumPy array of shape (4, 5) with random integers between 10 and 60.
# Perform the following operations:
# Extract the first two rows.
# Extract all elements in the last column.
# Replace all elements greater than 30 with 0.
# Calculate the sum of all elements in the array after replacement.
# Find the mean of each row.
# Add another row
# Print the result after each step

import numpy as np

# Create a 2D NumPy array of shape (4, 5) with random integers between 10 and 60
array_2d = np.random.randint(10, 61, size=(4, 5))
print("Original array:\n", array_2d)

# Extract the first two rows
first_two_rows = array_2d[:2, :]
print("\nFirst two rows:\n", first_two_rows)

# Extract all elements in the last column
last_column = array_2d[:, -1]
print("\nLast column:\n", last_column)

# Replace all elements greater than 30 with 0
array_2d[array_2d > 30] = 0
print("\nArray after replacing elements > 30 with 0:\n", array_2d)

# Calculate the sum of all elements in the array after replacement
sum_of_elements = np.sum(array_2d)
print("\nSum of all elements after replacement:\n", sum_of_elements)

# Find the mean of each row
row_means = np.mean(array_2d, axis=1)
print("\nMean of each row:\n", row_means)

# Add another row (e.g., a row of ones)
new_row = np.ones(5, dtype=int)
array_2d = np.vstack((array_2d, new_row))
print("\nArray after adding a new row:\n", array_2d)

Original array:
 [[51 12 31 36 57]
 [59 23 40 49 49]
 [52 32 52 25 34]
 [51 10 13 32 44]]

First two rows:
 [[51 12 31 36 57]
 [59 23 40 49 49]]

Last column:
 [57 49 34 44]

Array after replacing elements > 30 with 0:
 [[ 0 12  0  0  0]
 [ 0 23  0  0  0]
 [ 0  0  0 25  0]
 [ 0 10 13  0  0]]

Sum of all elements after replacement:
 83

Mean of each row:
 [2.4 4.6 5.  4.6]

Array after adding a new row:
 [[ 0 12  0  0  0]
 [ 0 23  0  0  0]
 [ 0  0  0 25  0]
 [ 0 10 13  0  0]
 [ 1  1  1  1  1]]


In [ ]:
# prompt: Write a regex to match a 5-digit zip code.
# Example: "90210" should match.

import re

def is_valid_zip(zip_code):
  """
  Checks if the given string is a valid 5-digit zip code using a regular expression.

  Args:
    zip_code: The string to check.

  Returns:
    True if the string is a valid 5-digit zip code, False otherwise.
  """
  pattern = r"^\d{5}$"  # Matches exactly 5 digits
  match = re.match(pattern, zip_code)
  return bool(match)

# Example usage
zip_code = "90210"
if is_valid_zip(zip_code):
  print(f"'{zip_code}' is a valid 5-digit zip code.")
else:
  print(f"'{zip_code}' is not a valid 5-digit zip code.")

zip_code = "90210-1234"  # Example of an invalid zip code
if is_valid_zip(zip_code):
  print(f"'{zip_code}' is a valid 5-digit zip code.")
else:
  print(f"'{zip_code}' is not a valid 5-digit zip code.")

'90210' is a valid 5-digit zip code.
'90210-1234' is not a valid 5-digit zip code.
